name: bluid docker image

permissions:
  packages: write

on:
    push:
      branches:
        - 'main'
    workflow_call:
      inputs:
        runner:
          description: 'The github runner to use'
          default: 'ubuntu-latest'
          required: false 
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Docker Login
        run: |
          export CR_PAT=10
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push
        run: |
          cd docker/build
          docker build -t ghcr.io/EvertBunschoten/PINNTraining_test:latest . 
          docker push ghcr.io/EvertBunschoten/PINNTraining_test:latest