name: Regression and Unit Testing

on:
  push:
    branches:
      - 'main'
  workflow_call:
    inputs:
      runner:
        description: 'The github runner to use'
        default: 'ubuntu-latest'
        required: false 
        type: string
jobs:
  build:
    name: build package
    strategy: 
      fail-fast: false
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    steps:
      - name: Say hi
        run: echo "hi there"

      - name: Docker Login
        run: |
          export CR_PAT=${{ secrets.DOCKER_TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin