name: Regression and Unit Testing

on:
  push:
    branches:
      - 'main'
  workflow_call:
    inputs:
      runner:
        description: 'The github runner to use'
        default: 'ubuntu-latest'
        required: false 
        type: string
jobs:
  build:
      name: Self Docker
      strategy: 
        fail-fast: false
      runs-on: 'ubuntu-latest'
